api:
  port: 9090
  host: 127.0.0.1
database:
  path: /can/be/used/for/sqlite.db
  port: "5432"
  password: "password"
  host: "localhost"
  name: "testdb"
  user: "postgres"
cache:
  address: localhost
  password: "password"
  db: 0
  max_tweets_to_keep: 1000
  tweet_expire_time_minutes: 1440 # 1 day in minutes
  user_feed_expire_time_minutes: 300 # just 5 hours 
  tweet_timeline_expire_time_minutes: 100
  max_tweets_timeline_items: 10
wss:
  port: 8080
  host: 127.0.0.1
  api: http://api:15001
metrics:
  port: 9091
  host: 127.0.0.1