name: Lint and build

on:
  push:
  pull_request:
  release:
    types:
      - created  # Trigger on new GitHub release (for Docker build)

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Download Go Modules
        run: go mod download

      - name: Tidy Go Modules
        run: go mod tidy

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

      - name: Run golangci-lint
        run: |
          $(go env GOPATH)/bin/golangci-lint run
